### ISSUE TITLE
Build with RST cannot find rst/geometry/Primitive3DFloatSet.proto

### ISSUE THREAD

**Issue by vrichter** [iclcv/icl#24]
Building icl-10.0.0 with RST produces the following error:
```
CMake Error at CMakeLists.txt:849 (MESSAGE):
  Could NOT find RST (missing: rst/geometry/Primitive3DFloatSet.proto)
```

I could not find Primitive3DFloatSet.proto in the official RST distribution too.
Which version is supposed to be used by icl-10.0.0?

**Comment by rhaschke** [comment]
We use our own RST repo: https://projects.cit-ec.uni-bielefeld.de/git/lspfamula.rst.git.

**Comment by aleneum** [comment]
As Robert mentioned `Primitive3DFloatSet` is not part of the official RST. Imho, having a custom RST 'just' for an example app is quite much. Considering the fact that the ICL already ships with custom protocol definitions I went ahead and added `Primitive3DFloat` and `Primitive3DFloatSet` to the 'built-in' RST definitions in `ICLGeom`. Much like `RSBImage` and `RSBPointCloud` these definitions are meant for ICL-internal usage and/or illustrational purpose. To prevent interference with type definitions in the rst-famula-proto both  types reside in the `icl.geom` namespace.

On the long run it might be preferable to move all protocol definitions into a) the official RST or b) adding them to `rst_experimental` when it becomes public (which it currently isnt, right?).

**Comment by aleneum** [comment]
Just a remark: RST is **not** required for sending ICL images via RSB since the used protocol definition `RSBImage` has no RST-specific dependencies.

**Comment by aleneum** [comment]
@vrichter: Please try again after updating your codebase from `master`. Compiling the ICL with `BUILD_WITH_RST` and `BUILD_APPS` should now succeed.

**Comment by vrichter** [comment]
https://github.com/iclcv/icl/commit/02789b8c01c222cf119891bffff3f4904e5de277 builds with BUILD_WITH_RST and BUILD_APPS. Thank You
